# Configuración de conexión a la base de datos MySQL
spring.datasource.url=jdbc:postgresql://ep-young-breeze-ap9tcav0-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Jg9sq2BLUQXe
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración para que Hibernate (Spring) cree la estructura automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true