# Configuración de conexión a la base de datos MySQL
spring.datasource.url=${postgresql://postgres:KmPWovpLqjnphHJJzMHRJeSvcHsBTFmR@postgres.railway.internal:5432/railway}
spring.datasource.username=${postgres}
spring.datasource.password=${KmPWovpLqjnphHJJzMHRJeSvcHsBTFmR}
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración para que Hibernate (Spring) cree la estructura automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Implemento esto para ahorro de datos railway
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000