spring.datasource.url=jdbc:postgresql://thomas.proxy.rlwy.net:52801/railway?sslmode=require&TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=KmPWovpLqjnphHJJzMHRJeSvcHsBTFmR
whatsapp.number=543854088612
